# Generated by Django 5.0.2 on 2024-03-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf', models.TextField(default=0, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nasc', models.DateField(null=True)),
                ('telefone', models.IntegerField()),
                ('pacote', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('nome_exercicio', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('nome', models.TextField(max_length=255, primary_key=True, serialize=False)),
                ('grupo_muscular', models.TextField(max_length=255)),
                ('marca', models.TextField(max_length=255)),
                ('data_compra', models.DateField()),
                ('ult_manutencao', models.DateField()),
                ('fornecedor', models.TextField(max_length=255)),
                ('prazo_manutencao', models.DateField()),
                ('prox_manutencao', models.DateField()),
                ('responsavel', models.TextField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False)),
                ('treino', models.TextField(max_length=255)),
                ('data_criacao', models.CharField(default='06/03/2024', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.aluno')),
                ('exercicios', models.ManyToManyField(to='app_academia.exercicio')),
            ],
        ),
    ]
