# Generated by Django 5.0.2 on 2024-02-18 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('CPF', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('telefone', models.IntegerField()),
                ('pacote', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('nome_exercicio', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False)),
                ('treino', models.TextField(max_length=255)),
                ('data_criacao', models.CharField(default='18/02/2024', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.aluno')),
                ('exercicios', models.ManyToManyField(to='app_academia.exercicio')),
            ],
        ),
    ]
