# Generated by Django 5.0.2 on 2024-02-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.TextField(max_length=255)),
                ('treino', models.TextField(max_length=255)),
            ],
        ),
    ]
