# Generated by Django 5.0.2 on 2024-02-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_academia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treinos',
            new_name='Treino',
        ),
    ]
