# Generated by Django 5.0.2 on 2024-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='data_criacao',
            field=models.CharField(default='25/02/2024', max_length=10),
        ),
    ]
