# Generated by Django 5.0.2 on 2024-02-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academia', '0002_alter_treino_data_criacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nome_aluno',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='CPF',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.TextField(default=0, primary_key=True, serialize=False),
        ),
    ]
