# Generated by Django 5.0.2 on 2024-02-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academia', '0002_rename_treinos_treino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('data_nasc', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('nome_exercicio', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='treino',
            name='data_criacao',
            field=models.CharField(default='17/02/2024', max_length=10),
        ),
        migrations.AlterField(
            model_name='treino',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.aluno'),
        ),
        migrations.AddField(
            model_name='treino',
            name='exercicios',
            field=models.ManyToManyField(to='app_academia.exercicio'),
        ),
    ]
